### ISSUE TITLE
get url timeout

### ISSUE THREAD

**Issue by jhautefeuille** [SlyMarbo/rss#19]
Is ti possible to add timeout when fetching url ?

Like as

http://stackoverflow.com/questions/16895294/how-to-set-timeout-for-http-get-requests-in-golang

**Comment by SlyMarbo** [comment]
Sorry for the very slow response.

Yes, you can add a timeout by modifying the client used to fetch the URL. If you use `rss.Fetch`, then `http.DefaultClient` is used, otherwise you can specify your own client in `rss.FetchClient`. Either way, modify the client to add a timeout with `client.Timeout = 5 * time.Second`, for example.
