### ISSUE TITLE
Incorrect parsing of RSS 1.0?

### ISSUE THREAD

**Issue by victorhaggqvist** [SlyMarbo/rss#20]
I'm trying to read http://www.freenas.org/whats-new/feed. But it seems like the item `<description>` ends up as `item.Content` and `item.Summary` is empty.

I would think expected behavior is `<description>` as `item.Summary` and `<content:encoded>` as `item.Content`.

**Comment by SlyMarbo** [comment]
I agree it's a little odd, but the library does seem to be conforming to [the spec](http://www.rssboard.org/rss-specification#hrelementsOfLtitemgt). The header at the beginning looks strange though, since it's correct for RSS/2.0, but also mentions RSS/1.0, and Atom.

I'd say this is a poorly-formed feed.

**Comment by victorhaggqvist** [comment]
Oh well, thanks anyhow.
