### ISSUE TITLE
Problem with Feed Link attribute

### ISSUE THREAD

**Issue by rbatukaev** [SlyMarbo/rss#23]
I can successfully parse `http://www.ft.com/rss/home/europe` feed, except that the `Feed.Link` attribute is the same as RSS feed address. So:

RSS address is http://www.ft.com/rss/home/europe
`<link>` attribute in the RSS feed is http://www.ft.com/home/europe
`Feed.Link` value is http://www.ft.com/rss/home/europe (same as RSS address, not as `<link>` attribute in the RSS feed)

I had the same issue with some other feeds as well.

**Comment by rbatukaev** [comment]
Please visit the [pull request](https://github.com/SlyMarbo/rss/pull/24) that seems to fix this issue.

**Comment by SlyMarbo** [comment]
When I parse the feed (using `go run debug.go 'http://www.ft.com/rss/home/europe'`), I get `"http://www.ft.com/rss/home/europe"` for the Link attribute, which seems to be what you're expecting. Could you try the same?

**Comment by rbatukaev** [comment]
I actually expect a different link.

http://www.ft.com/rss/home/europe  - RSS Feed Link
http://www.ft.com/home/europe - `<link>` tag value

Notice the missing `/rss` path.

**Comment by SlyMarbo** [comment]
Ah, yes, my mistake. I'll try and track down why it's happening.

**Comment by rbatukaev** [comment]
Thank you. I have updated my pull request. Please review it, as it actually solves my problem.

**Comment by SlyMarbo** [comment]
Yeah, the reason the problem is occurring is that the feed contains both a `<link>` element and a `<atom:link>` element. The `encoding/xml` package is treating these as both `<link>` elements, so it treats it as an array. As a result, just a single `string` field is ignored, but it works correctly with a `[]string` field. I'll accept your pull request; it looks pretty good :)
