### ISSUE TITLE
10 minute refresh

### ISSUE THREAD

**Issue by mnot** [SlyMarbo/rss#81]
The docs say that 10 minutes is the default refresh period, and for Atom feeds it looks like the only possible refresh period (because Atom doens't have a `ttl` element).

This is very aggressive -- if your library is used in a popular application and it polls a popular feed (especially an Atom feed), it would create a lot of load and traffic.

Can I suggest that the default be changed to something like 12 or 24 hours? That fits the use case for most feeds much better. 

Also, the feed response can have an explicit [freshness lifetime](https://httpwg.org/specs/rfc9111.html#expiration.model) -- if it's there, it'd be good to use it. E.g., if the response says `Cache-Control: max-age=3600`, there's no reason to poll the feed for the next hour (taking into account the `Age` header, in case it was cached upstream).

**Comment by SlyMarbo** [comment]
Yes, great point. I'll investigate. At a minimum, I'll update the package to honour `Cache-Control` headers as that's a no-brainer. I'll also see whether the default period is a variable (making it easier for integrators to change it) and revisit the default value.

**Comment by SlyMarbo** [comment]
I've made the change, but I'm having an issue with my dev machine and can't push the changes. I'll try and get this fixed in the next day or two. Sorry for the delay.

**Comment by SlyMarbo** [comment]
I've pushed a partial fix, which is now `v1.0.5`. This exposes the default refresh interval so that it can be changed by callers of the package. It also changes the default interval from 10 minutes to 12 hours.

Unfortunately, it wasn't possible to use HTTP cache headers, due to some poor API design decisions I made many years ago. If I were to break the API to fix that, I would make many other API changes, which would be a v2 of the package and a lot of work. Sadly, I don't have time to do that, so it's unlikely to happen any time soon.

Hopefully, this should still be a sufficient fix. Please feel free to reopen the issue if you feel this isn't enough. Thanks again.
